#!/bin/bash

echo "Installing Python 3 virtual environment in ./venv ..."
python3 -m venv venv

echo "Installing dev dependencies..."
source venv/bin/activate
pip3 install --upgrade pip
pip3 install flask
pip3 install requests
deactivate

echo "Done. Use venv/bin/activate to enter the virtual environment."
